// Each module in the Equation Composer should be included here.
// This file is included in Synths.h

#include "Module.h"
#include "ModuleOutput.h"
#include "ModuleAdd.h"
#include "ModuleArpeggio.h"
#include "ModuleBitReducer.h"
#include "ModuleClock.h"
#include "ModuleClockedRandom.h"
#include "ModuleClockDivider.h"
#include "ModuleConstant.h"
#include "ModuleCounter.h"
#include "ModuleDelay.h"
#include "ModuleDrumSequencer.h"
#include "ModuleENV.h"
#include "ModuleEqDrum.h"
#include "ModuleEquationPlayer.h"
#include "ModuleEquationLooper.h"
#include "ModuleExtClock.h"
#include "ModuleHighpassFilter.h"
#include "ModuleLFO.h"
#include "ModuleLowpassFilter.h"
#include "ModuleMap.h"
#include "ModuleMixer2.h"
#include "ModuleMixer3.h"
#include "ModuleMultiply.h"
#include "ModulePatternGenerator.h"
#include "ModuleQuantizer.h"
#include "ModuleSampleAndHold.h"
#include "ModuleSequencer.h"
#include "ModuleSmooth.h"
#include "ModuleSwitch.h"
#include "ModuleVCA.h"
#include "ModuleWavetableOsc.h"
#include "ModuleWords.h"